Repository spyder-ide/spyder, pull requests merged in 2018-11, with the labels that each got.

#8123 PR: Improve usability of runtests locally and test output on the CIs
  runtests.py
Labels: type:Task

#8158 PR: Fix font color in dark theme for several widgets
  spyder/plugins/findinfiles/plugin.py
  spyder/plugins/findinfiles/tests/test_widgets.py
  spyder/plugins/findinfiles/widgets.py
  spyder/plugins/lspmanager.py
  spyder/preferences/shortcuts.py
  spyder/widgets/fileswitcher.py
Labels: status:Work In Progress, tag:Ui, type:Enhancement

#8197 PR: Add parent reference to dialogs to ensure correct setup of the dark theme
  spyder/app/mainwindow.py
  spyder/plugins/profiler/widgets/profilergui.py
  spyder/widgets/github/backend.py
  spyder/widgets/reporterror.py
Labels: tag:Ui, type:Enhancement

#7205 PR: Unmaximize plugins when an action or menu calls another plugin
  spyder/app/mainwindow.py
  spyder/plugins/__init__.py
  spyder/plugins/editor.py
  spyder/plugins/help.py
  spyder/plugins/ipythonconsole.py
  spyder/plugins/projects.py
  spyder/plugins/tests/test_help.py
  spyder/plugins/tests/test_ipythonconsole.py
  spyder/plugins/tests/test_projects.py
  spyder/widgets/ipythonconsole/namespacebrowser.py
  spyder_breakpoints/breakpoints.py
  spyder_profiler/profiler.py
  spyder_pylint/pylint.py
Labels: component:Main Window, tag:Ui, type:Bug

#8212 PR: Add system-specific shortcut names on macOS to the Shortcuts summary dialog
  spyder/widgets/shortcutssummary.py
  spyder/widgets/tests/test_shortcutssummary.py
Labels: OS:MacOS, tag:Ui, type:Enhancement

#8201 PR: Missing dark style for QMenus, Tour, Pylint, Profiler and DataFrameEditor
  spyder/app/mainwindow.py
  spyder/app/tour.py
  spyder/config/gui.py
  spyder/plugins/plots/plugin.py
  spyder/plugins/plots/widgets/figurebrowser.py
  spyder/plugins/profiler/plugin.py
  spyder/plugins/profiler/widgets/profilergui.py
  spyder/plugins/pylint/plugin.py
  spyder/plugins/pylint/widgets/pylintgui.py
  spyder/plugins/variableexplorer/widgets/dataframeeditor.py
  spyder/utils/icon_manager.py
Labels: tag:Ui, type:Enhancement

#8249 PR: Prevent an error during the initialization of the Editor plugin
  spyder/plugins/editor.py
Labels: component:Editor, type:Bug

#8266 PR: Centralize theme-related preferences under an 'Appearance' entry
  spyder/api/plugins.py
  spyder/app/mainwindow.py
  spyder/config/gui.py
  spyder/config/main.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/lspmanager.py
  spyder/preferences/configdialog.py
  spyder/utils/icon_manager.py
  spyder/utils/syntaxhighlighters.py
  spyder/widgets/reporterror.py
Labels: tag:Ui, type:Enhancement

#8272 PR: Greatly simplify and clarify Github pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status:Ready For Review, type:Task

#8299 PR: Improve contributing guide
  CONTRIBUTING.md
  requirements/conda.txt
  requirements/pip.txt
  requirements/tests.txt
  setup.py
Labels: type:Task

#8300 PR: Add qdarkstyle to dependencies dialog
  spyder/app/mainwindow.py
Labels: type:Task

#8222 PR: Save last accepted kernel settings in config
  spyder/plugins/ipythonconsole/widgets/kernelconnect.py
  spyder/plugins/ipythonconsole/widgets/tests/test_kernelconnect.py
Labels: component:IPython Console, tag:Ux-usability, type:Enhancement
