Repository spyder-ide/spyder, pull requests merged in 2018-09, with the labels that each got.

#7789 PR: Add "find_replace" widget to qtbot in fixtures of "test_editor.py"
  spyder/plugins/editor/widgets/tests/test_editor.py
Labels: type:Techdebt

#7799 PR: Remove file from the outline explorer when it is closed
  spyder/plugins/editor/widgets/editor.py
  spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
  spyder/plugins/outlineexplorer/widgets.py
Labels: component:Outline Explorer, severity:3-Moderate, type:Bug

#7826 PR: Conform short dates dates to be properly ISO 8601
  spyder/plugins/profiler/widgets/profilergui.py
  spyder/plugins/pylint/widgets/pylintgui.py
  spyder/utils/syntaxhighlighters.py
Labels: type:Task

#7768 PR: Improve how keyboard shortcuts are handled in the Editor
  spyder/config/main.py
  spyder/plugins/editor/widgets/codeeditor.py
  spyder/plugins/editor/widgets/editor.py
  spyder/plugins/editor/widgets/tests/test_shortcuts.py
  spyder/preferences/shortcuts.py
Labels: type:Enhancement

#7835 PR: Refactor test_autoindent.py to make the pytest logs cleaner
  spyder/plugins/editor/widgets/tests/test_autoindent.py
Labels: type:Techdebt

#7852 PR: Remove '--cov-report=term-missing' from pytest args
  runtests.py
Labels: type:Task

#7829 PR: Use a function to create and get our temporary directory
  spyder/app/mainwindow.py
  spyder/plugins/ipythonconsole.py
  spyder/plugins/tests/test_ipythonconsole.py
  spyder/utils/misc.py
  spyder/utils/programs.py
  spyder/utils/tests/test_programs.py
  spyder/widgets/ipythonconsole/client.py
Labels: type:Bug

#7873 PR: Correct next/previous word shortcut callback
  spyder/widgets/sourcecode/codeeditor.py
Labels: component:Editor, severity:4-Low, type:Bug

#7874 PR: Correct next/previous word shortcut callback in Spyder 4
  spyder/config/main.py
  spyder/plugins/editor/widgets/codeeditor.py
  spyder/plugins/editor/widgets/tests/test_shortcuts.py
Labels: component:Editor, severity:4-Low, type:Bug

#7864 PR: More improvements to Find in Files
  NOTICE.txt
  spyder/config/main.py
  spyder/images/regexp.svg
  spyder/plugins/tests/test_findinfiles.py
  spyder/utils/misc.py
  spyder/widgets/findinfiles.py
  spyder/widgets/findreplace.py
  spyder/widgets/tests/test_findinfiles.py
Labels: component:Find in files, tag:Ux-usability, type:Enhancement

#7888 PR: Remove old pdn image source files that are no longer needed
  img_src/execute_interact.pdn
  img_src/execute_selection.pdn
  img_src/ws_new.pdn
  img_src/ws_open.pdn
  img_src/ws_save.pdn
  img_src/ws_save_as.pdn
Labels: status:Ready For Review, type:Task

#7876 PR: Reinitialize Pylab, Sympy and Cython after clearing all variables
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/variableexplorer/widgets/namespacebrowser.py
Labels: component:IPython Console, type:Enhancement

#7898 PR: Clarify and improve Connect to kernel dialog text
  spyder/plugins/ipythonconsole.py
Labels: component:IPython Console, status:Ready For Review, tag:Documentation, tag:Ui, type:Enhancement

#7928 PR: Update PR template to link to developer COI and clarify other text
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status:Ready For Review, type:Task

#7927 PR: Convert and optimize tutorial PNGs and profiler/pylint icons
  spyder/plugins/help/utils/static/images/collapse_expand.png
  spyder/plugins/help/utils/static/images/debug-continue.png
  spyder/plugins/help/utils/static/images/debug-step-in.png
  spyder/plugins/help/utils/static/images/debug-step-out.png
  spyder/plugins/help/utils/static/images/debug-step-over.png
  spyder/plugins/help/utils/static/images/spyder-hello-docstring.png
  spyder/plugins/help/utils/static/images/spyder-nice-docstring-rendering.png
  spyder/plugins/help/utils/static/images/spyder-sympy-example.png
  spyder/plugins/profiler/images/profiler.png
  spyder/plugins/pylint/images/pylint.png
Labels: status:Ready For Review, type:Task

#7926 PR: Convert and optimize needed PNGs in img_src directory
  img_src/screenshot.png
  img_src/spyder.png
  img_src/spyder3.png
  img_src/spyder_readme_banner.png
Labels: status:Ready For Review, type:Task

#7954 PR: Improve how keyboard shortcuts are handled in the Editor (Take 2)
  spyder/plugins/editor/widgets/codeeditor.py
  spyder/plugins/editor/widgets/editor.py
  spyder/plugins/editor/widgets/tests/test_shortcuts.py
Labels: component:Editor, status:Ready For Review

#7962 PR: Improvement to navigation and file switching in the Outline Explorer
  spyder/plugins/editor/widgets/tests/test_editor_and_outline.py
  spyder/plugins/outlineexplorer/widgets.py
Labels: component:Outline Explorer, status:Ready For Review, type:Enhancement
