Repository spyder-ide/spyder, pull requests merged in 2018-06, with the labels that each got.

#7234 PR: Call garbage collector from Main Window after closing Variable Explorer editors
  spyder/app/mainwindow.py
  spyder/plugins/variableexplorer.py
  spyder/widgets/variableexplorer/collectionseditor.py
  spyder/widgets/variableexplorer/namespacebrowser.py
Labels: component:Variable Explorer

#7262 PR: Update donation/funding status message in Readme
  README.md
Labels: status:Ready For Review, type:Task

#7278 PR: Fix links to Travis CI and Google Group
  README.md
Labels: type:Task

#7254 PR: Prevent realtime code analysis failures due to encoding errors
  spyder/tests/test_dont_use.py
  spyder/utils/codeanalysis.py
  spyder/utils/encoding.py
  spyder/utils/tests/data/example_latin1.py
  spyder/utils/tests/test_codeanalysis.py
Labels: type:Bug

#7007 PR: Update links to docs when they are ready
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  spyder/app/mainwindow.py
Labels: status:Work In Progress, tag:Documentation, type:Task

#7132 PR: Limit the number of lines in history according to the relevant setting
  spyder/plugins/history.py
  spyder/plugins/tests/test_history.py
  spyder/utils/sourcecode.py
  spyder/utils/tests/test_sourcecode.py
Labels: component:History Log, type:Bug

#7335 PR: Handle deprecated Pandas methods in tests
  spyder/widgets/variableexplorer/tests/test_collectioneditor.py
  spyder/widgets/variableexplorer/tests/test_dataframeeditor.py
Labels: component:Variable Explorer
