Repository spyder-ide/spyder, pull requests merged in 2018-07, with the labels that each got.

#7418 PR: Update the running Github clone procedure in the readme and contributing guide to include spyder-kernels
  CONTRIBUTING.md
  README.md
Labels: tag:Documentation, type:Task

#7478 PR: Change way to check for updates
  spyder/workers/tests/test_update.py
  spyder/workers/updates.py
Labels: tag:Ux-usability, type:Enhancement

#7500 PR: Handle input commands correctly in the internal console.
  spyder/widgets/internalshell.py
Labels: type:Bug

#7505 PR: Add support for numeric literals with underscores highlighting in Python 3.6
  spyder/py3compat.py
  spyder/utils/syntaxhighlighters.py
Labels: component:Editor

#7546 PR: Do not automatically open Project Explorer when opening project if user closed it
  spyder/config/main.py
  spyder/plugins/projects.py
  spyder/plugins/tests/test_projects.py
Labels: component:Projects, status:Ready For Review, type:Bug

#7300 PR: Do not save pdb commands in debugging history
  spyder/widgets/ipythonconsole/debugging.py
Labels: component:History Log, type:Enhancement

#7582 PR: Update setup.py description, metadata, links, and more
  setup.py
  spyder/__init__.py
Labels: status:Ready For Review, tag:Documentation, type:Task
