Repository spyder-ide/spyder, pull requests merged in 2018-02, with the labels that each got.

#6434 PR: Handle errors when writing history to disk in the IPython Console
  spyder/widgets/mixins.py
Labels: component:IPython Console, type:Bug

#6413 PR: Add test for file directory change in the Project Explorer.
  spyder/widgets/explorer.py
  spyder/widgets/projects/explorer.py
  spyder/widgets/projects/tests/test_project_explorer.py
Labels: component:File Explorer, component:Projects, status:Pending Changes/Test, type:Task

#6468 PR: Update broken matplotlib project URL in install doc
  doc/installation.rst
Labels: tag:Documentation, type:Task

#6154 PR: Add troubleshooting blurb and OS version to issue template and enhance UI
  .github/ISSUE_TEMPLATE.md
  spyder/__init__.py
  spyder/app/mainwindow.py
  spyder/app/tests/test_mainwindow.py
  spyder/plugins/console.py
  spyder/widgets/reporterror.py
  spyder/widgets/tests/test_dependencies.py
  spyder/widgets/tests/test_reporterror.py
Labels: status:Ready For Review, tag:Documentation, tag:Ui, type:Task

#6473 PR: Skip test_completions_custom_path if jedi version before 0.10.0
  spyder/utils/introspection/tests/test_jedi_plugin.py
Labels: component:Code Completion

#6497 PR: Bump required version for Jedi to 0.11.0
  README.md
  conda.recipe/meta.yaml
  doc/installation.rst
  requirements/requirements.txt
  setup.py
  spyder/plugins/help.py
  spyder/plugins/tests/test_editor_introspection.py
  spyder/utils/introspection/jedi_patch.py
  spyder/utils/introspection/jedi_plugin.py
  spyder/utils/introspection/manager.py
  spyder/utils/introspection/numpy_docstr.py
  spyder/utils/introspection/tests/test_jedi_plugin.py
Labels: component:Code Completion, status:Ready For Review, type:Techdebt

#6523 PR: Fix AttributeError in jedi_plugin
  spyder/utils/introspection/jedi_plugin.py
  spyder/utils/introspection/tests/test_jedi_plugin.py
Labels: component:Code Completion, status:Ready For Review, type:Bug

#6528 PR: Restore the previous wording for package versions in error report
  spyder/app/mainwindow.py
Labels: component:Main Window, tag:Ux-usability, type:Task
