Repository spyder-ide/spyder, pull requests merged in 2021-12, with the labels that each got.

#16941 PR: Move DPI change message dialog to the primaryScreen center
  spyder/plugins/application/container.py
Labels: type:Bug, component:Main Window

#16950 PR: Clear highlighted matches after clearing text in find widget (Editor)
  spyder/widgets/findreplace.py
Labels: type:Bug, tag:Ui, component:Find and Replace

#16977 PR: Fix option to maintain focus on editor after running cells or selections
  spyder/app/tests/test_mainwindow.py
  spyder/plugins/editor/plugin.py
  spyder/plugins/editor/widgets/editor.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Bug, component:Editor, component:IPython Console

#16983 PR: Update translations for 5.2.1
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Task

#17012 PR: Update Quansight logo in Readme
  README.md
Labels: type:Task

#17015 PR: Update CI workflows to use macOS 10.15
  .github/workflows/installer-macos.yml
  .github/workflows/test-mac.yml
Labels: type:Task

#17009 PR: Remove `check_spyder_kernels`
  spyder/app/mainwindow.py
  spyder/requirements.py
Labels: type:Task

#17010 PR: Update core dependencies for 5.2.1
  binder/environment.yml
  external-deps/python-lsp-server/.gitrepo
  external-deps/python-lsp-server/.pylintrc
  external-deps/python-lsp-server/CHANGELOG.md
  external-deps/python-lsp-server/pylsp/plugins/_resolvers.py
  external-deps/python-lsp-server/pylsp/plugins/rope_completion.py
  external-deps/python-lsp-server/test/plugins/test_pylint_lint.py
  requirements/conda.txt
  setup.py
  spyder/dependencies.py
Labels: type:Task

#17003 PR: Many updates to third party file lists in NOTICE.txt
  NOTICE.txt
Labels: type:Task

#17056 PR: Add validation for registration/unregistration of completion provider status bar widgets
  spyder/plugins/completion/container.py
  spyder/plugins/completion/plugin.py
Labels: type:Bug, component:Code Completion, component:Main Window
