Repository spyder-ide/spyder, pull requests merged in 2021-11, with the labels that each got.

#16753 PR: Allow console restart when reopening projects at startup
  spyder/plugins/projects/plugin.py
Labels: component:Projects

#16787 PR: Add missing argument to shortcut preferences
  spyder/plugins/shortcuts/confpage.py
Labels: type:Bug, component:Preferences

#16801 PR: Update RELEASE.md and CONTRIBUTING.md
  CONTRIBUTING.md
  RELEASE.md
Labels: type:Task

#16831 PR: Fix some issues after the IPython Console migration
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Bug, component:IPython Console

#16855 PR: Update missing translation strings for next release
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
  spyder/plugins/projects/widgets/projectdialog.py
Labels: type:Task

#16848 PR: Prevent some plugins from being disabled
  spyder/plugins/completion/confpage.py
  spyder/plugins/console/plugin.py
  spyder/plugins/layout/plugin.py
  spyder/plugins/maininterpreter/plugin.py
  spyder/plugins/mainmenu/plugin.py
  spyder/plugins/preferences/plugin.py
  spyder/plugins/shortcuts/plugin.py
  spyder/plugins/statusbar/confpage.py
  spyder/plugins/toolbar/plugin.py
  spyder/plugins/workingdirectory/plugin.py
Labels: type:Enhancement

#16895 PR: Update RELEASE and MAINTENANCE files and fix some IPython Console issues
  MAINTENANCE.md
  RELEASE.md
  spyder/plugins/ipythonconsole/widgets/client.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console, tag:Documentation

#16915 PR: Fix error when updating the plugin checkboxes state
  spyder/api/plugin_registration/_confpage.py
Labels: type:Bug, component:Preferences
