Repository spyder-ide/spyder, pull requests merged in 2023-12, with the labels that each got.

#21573 PR: Increase minimal required version of PyQt to 5.15
  .github/scripts/install.sh
  README.md
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/requirements.py
Labels: type:Task

#21572 PR: Initial fixes to make Spyder work with Qt 6
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/app/mainwindow.py
  spyder/app/utils.py
  spyder/config/gui.py
  spyder/dependencies.py
  spyder/plugins/completion/plugin.py
  spyder/plugins/editor/extensions/tests/test_docstring.py
  spyder/plugins/editor/utils/editor.py
  spyder/plugins/editor/widgets/base.py
  spyder/plugins/editor/widgets/codeeditor/codeeditor.py
  spyder/plugins/editor/widgets/printer.py
  spyder/plugins/editor/widgets/recover.py
  spyder/plugins/explorer/widgets/fileassociations.py
  spyder/plugins/layout/plugin.py
  spyder/plugins/layout/widgets/dialog.py
  spyder/plugins/preferences/widgets/config_widgets.py
  spyder/plugins/shortcuts/widgets/summary.py
  spyder/plugins/shortcuts/widgets/table.py
  spyder/plugins/variableexplorer/widgets/arrayeditor.py
  spyder/plugins/variableexplorer/widgets/dataframeeditor.py
  spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
  spyder/plugins/workingdirectory/container.py
  spyder/requirements.py
  spyder/utils/qthelpers.py
  spyder/utils/tests/test_syntaxhighlighters.py
  spyder/widgets/browser.py
  spyder/widgets/calltip.py
  spyder/widgets/collectionseditor.py
  spyder/widgets/comboboxes.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/mixins.py
Labels: Package:PyQt, type:Task

#21574 PR: Some improvements to the Pythonpath plugin
  spyder/app/mainwindow.py
  spyder/app/tests/test_mainwindow.py
  spyder/plugins/externalterminal/plugin.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/pythonpath/container.py
  spyder/plugins/pythonpath/plugin.py
  spyder/plugins/pythonpath/widgets/pathmanager.py
Labels: type:Enhancement, component:Pythonpath manager

#21578 PR: Fix two tests for Python 3.11
  spyder/plugins/variableexplorer/widgets/objectexplorer/tests/test_objectexplorer.py
Labels: type:Task

#21581 PR: Fix list comprehension test for Python 3.12
  spyder/plugins/ipythonconsole/tests/conftest.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Labels: type:Task

#21580 PR: Fix regex quoting
  spyder/plugins/pythonpath/utils.py
Labels: type:Bug, component:Pythonpath manager

#21555 PR: Add new combobox widgets (API)
  spyder/api/widgets/comboboxes.py
  spyder/plugins/appearance/confpage.py
  spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
  spyder/plugins/completion/providers/snippets/conftabs.py
  spyder/plugins/completion/providers/snippets/widgets/snippetsconfig.py
  spyder/plugins/editor/panels/classfunctiondropdown.py
  spyder/plugins/findinfiles/widgets/combobox.py
  spyder/plugins/help/widgets.py
  spyder/plugins/layout/widgets/dialog.py
  spyder/plugins/preferences/widgets/config_widgets.py
  spyder/plugins/projects/widgets/projectdialog.py
  spyder/plugins/projects/widgets/qcookiecutter.py
  spyder/plugins/run/confpage.py
  spyder/plugins/run/widgets.py
  spyder/plugins/tours/widgets.py
  spyder/plugins/variableexplorer/widgets/arrayeditor.py
  spyder/utils/stylesheet.py
  spyder/widgets/comboboxes.py
  spyder/widgets/helperwidgets.py
Labels: type:Enhancement, User Interface (UI), User Experience (UX), component:Main Window

#21511 PR: Improve how menus are rendered and fix graphical errors related to them (UI)
  spyder/api/widgets/main_widget.py
  spyder/api/widgets/menus.py
  spyder/api/widgets/mixins.py
  spyder/app/tests/test_mainwindow.py
  spyder/config/gui.py
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/plugins/application/widgets/status.py
  spyder/plugins/completion/api.py
  spyder/plugins/completion/providers/languageserver/widgets/status.py
  spyder/plugins/completion/widgets/status.py
  spyder/plugins/console/widgets/shell.py
  spyder/plugins/debugger/widgets/breakpoint_table_view.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/plugins/editor/plugin.py
  spyder/plugins/editor/widgets/codeeditor/codeeditor.py
  spyder/plugins/editor/widgets/window.py
  spyder/plugins/ipythonconsole/api.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/widgets/client.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/layout/container.py
  spyder/plugins/mainmenu/api.py
  spyder/plugins/mainmenu/plugin.py
  spyder/plugins/plots/widgets/figurebrowser.py
  spyder/plugins/preferences/widgets/configdialog.py
  spyder/plugins/projects/widgets/main_widget.py
  spyder/plugins/shortcuts/plugin.py
  spyder/plugins/toolbar/container.py
  spyder/plugins/tours/widgets.py
  spyder/plugins/variableexplorer/widgets/arrayeditor.py
  spyder/plugins/variableexplorer/widgets/dataframeeditor.py
  spyder/plugins/variableexplorer/widgets/importwizard.py
  spyder/plugins/variableexplorer/widgets/objectexplorer/objectexplorer.py
  spyder/utils/icon_manager.py
  spyder/utils/qthelpers.py
  spyder/utils/stylesheet.py
  spyder/widgets/browser.py
  spyder/widgets/collectionseditor.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/printer.py
  spyder/widgets/tabs.py
Labels: type:Bug, type:Enhancement, OS:MacOS, User Interface (UI), component:Main Window

#21613 PR: Handle infowidget possible RuntimeError when hiding it (IPython Console)
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Bug, component:IPython Console

#21483 PR: Create `UpdateManager` plugin to handle updates for the conda-based installers
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
  setup.py
  spyder/api/plugins/enum.py
  spyder/config/main.py
  spyder/plugins/application/confpage.py
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/plugins/application/widgets/install.py
  spyder/plugins/application/widgets/status.py
  spyder/plugins/statusbar/plugin.py
  spyder/plugins/updatemanager/__init__.py
  spyder/plugins/updatemanager/api.py
  spyder/plugins/updatemanager/container.py
  spyder/plugins/updatemanager/plugin.py
  spyder/plugins/updatemanager/scripts/install.bat
  spyder/plugins/updatemanager/scripts/install.sh
  spyder/plugins/updatemanager/tests/__init__.py
  spyder/plugins/updatemanager/tests/test_update_manager.py
  spyder/plugins/updatemanager/widgets/__init__.py
  spyder/plugins/updatemanager/widgets/status.py
  spyder/plugins/updatemanager/widgets/update.py
  spyder/plugins/updatemanager/workers.py
  spyder/workers/tests/__init__.py
  spyder/workers/tests/test_update.py
  spyder/workers/updates.py
Labels: type:Enhancement, Installers

#21616 PR: Start spinner in dependencies dialog only when it's visible and make some improvements to its UI
  .github/scripts/modules_test.sh
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/utils/icon_manager.py
  spyder/utils/stylesheet.py
  spyder/widgets/dependencies.py
  spyder/widgets/helperwidgets.py
Labels: type:Bug, type:Enhancement, User Interface (UI)

#21624 PR: Catch error when the scrollbar has zero height in the scrollflag panel (Editor)
  spyder/plugins/editor/panels/scrollflag.py
Labels: type:Bug, component:Editor

#21628 PR: Update core dependencies for 6.0.0.alpha3
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  external-deps/spyder-kernels/spyder_kernels/comms/commbase.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Task

#21629 PR: Increase minimal required version of `python-lsp-black` to `>=2.0.0,<3.0.0`
  .github/scripts/install.sh
  .github/workflows/installer-macos.yml
  binder/environment.yml
  external-deps/python-lsp-server/.gitrepo
  external-deps/python-lsp-server/README.md
  external-deps/python-lsp-server/pylsp/plugins/flake8_lint.py
  external-deps/python-lsp-server/pylsp/plugins/jedi_completion.py
  external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py
  external-deps/python-lsp-server/pylsp/plugins/rope_autoimport.py
  external-deps/python-lsp-server/pylsp/python_lsp.py
  external-deps/python-lsp-server/pylsp/workspace.py
  external-deps/python-lsp-server/pyproject.toml
  external-deps/python-lsp-server/test/plugins/test_autoimport.py
  external-deps/python-lsp-server/test/plugins/test_completion.py
  external-deps/python-lsp-server/test/plugins/test_flake8_lint.py
  external-deps/python-lsp-server/test/test_notebook_document.py
  installers/macOS/packages.py
  installers/macOS/req-build.txt
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Enhancement, component:Editor, component:Code Completion and linting

#21622 PR: Make some UI/UX improvements to the Find pane
  spyder/plugins/findinfiles/plugin.py
  spyder/plugins/findinfiles/tests/test_plugin.py
  spyder/plugins/findinfiles/widgets/combobox.py
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/findinfiles/widgets/tests/test_widgets.py
Labels: type:Bug, type:Enhancement, User Interface (UI), User Experience (UX), component:Find in files

#21641 PR: Additional UI improvements to the `About Spyder` dialog
  .github/scripts/modules_test.sh
  spyder/api/widgets/mixins.py
  spyder/app/utils.py
  spyder/plugins/application/container.py
  spyder/plugins/application/widgets/__init__.py
  spyder/plugins/application/widgets/about.py
  spyder/plugins/tours/widgets.py
  spyder/utils/icon_manager.py
  spyder/utils/stylesheet.py
  spyder/widgets/helperwidgets.py
Labels: type:Enhancement, User Interface (UI)

#21654 PR: Fix extra line in range when formatting selection
  spyder/plugins/editor/widgets/codeeditor.py
Labels: type:Bug, component:Editor
