Repository spyder-ide/spyder, pull requests merged in 2023-10, with the labels that each got.

#21403 PR: Fix compatibility with Python 2 environments (IPython console)
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/comms/frontendcomm.py
  external-deps/spyder-kernels/spyder_kernels/console/start.py
Labels: type:Bug, component:IPython Console

#21413 PR: Drop support for Python 3.7
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  README.md
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/requirements/posix.txt
  external-deps/spyder-kernels/requirements/windows.txt
  external-deps/spyder-kernels/setup.py
  requirements/main.yml
  setup.py
  spyder/app/tests/conftest.py
  spyder/app/tests/spyder-boilerplate/setup.py
  spyder/app/tests/test_mainwindow.py
  spyder/dependencies.py
  spyder/tests/test_dependencies_in_sync.py
Labels: type:Task

#21402 PR: Improve mechanism to check for updates and message that informs about them
  spyder/plugins/application/container.py
  spyder/utils/conda.py
  spyder/utils/tests/test_conda.py
  spyder/workers/tests/test_update.py
  spyder/workers/updates.py
Labels: type:Enhancement, component:Main Window

#21417 PR: Fix calling the `%debug` magic after an error (IPython console)
  .github/scripts/install.sh
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
Labels: type:Bug, component:Debugger, component:IPython Console

#21423 PR: Use `requests` instead of `urllib` for updates
  spyder/workers/updates.py
Labels: type:Enhancement, type:Techdebt

#21426 PR: Improve how we get signatures and catch error when trying to do it for certain objects (IPython console)
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/utils/dochelpers.py
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_dochelpers.py
  spyder/plugins/application/container.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/ipythonconsole/widgets/help.py
  spyder/workers/tests/test_update.py
Labels: type:Bug, type:Enhancement, component:IPython Console

#21424 PR: Change name of workflow for conda-based installers
  .github/workflows/installers-conda.yml
Labels: type:Task, Installers

#21433 PR: Follow-up to using the `requests` library for updates
  spyder/workers/updates.py
Labels: type:Enhancement

#21439 PR: Avoid pydev warning under all circumstances (Online help)
  spyder/plugins/onlinehelp/widgets.py
Labels: type:Bug, component:Online Help

#21442 PR: Update translations for 5.5.0
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/te/LC_MESSAGES/spyder.po
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Labels: type:Task

#21436 PR: Fix issue where statusbar status was not updated properly after checking for updates
  spyder/plugins/application/container.py
Labels: type:Bug, Installers

#21441 PR: Avoid error when restarting external kernel (IPython console)
  spyder/plugins/ipythonconsole/widgets/client.py
Labels: type:Bug, component:IPython Console

#21454 PR: Prevent errors when removing nested options values (Config)
  spyder/config/manager.py
Labels: type:Bug, component:Code Completion and linting, component:Preferences

#21457 PR: Escape backslashes when replacing all occurrences of some text by another with them (Find/Replace)
  spyder/widgets/findreplace.py
  spyder/widgets/tests/test_findreplace.py
Labels: type:Bug, component:Find and Replace

#21451 PR: Fix interface language auto-configuration
  spyder/config/base.py
Labels: type:Bug, component:Main Window

#21467 PR: Fix functions that need to parse conda output for its latest version (Utils)
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
  spyder/utils/conda.py
  spyder/utils/tests/test_conda.py
Labels: type:Bug, OS:Windows

#21461 PR: Backport PR #21451 (Fix interface language auto-configuration)
  spyder/config/base.py
Labels: type:Bug, component:Main Window

#21465 PR: Update minimal required version of QDarkstyle to `>=3.2,<3.3`
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/utils/icon_manager.py
  spyder/utils/stylesheet.py
Labels: type:Enhancement, User Interface (UI)

#21463 PR: Fix enabling/disabling individual providers (Completions)
  spyder/plugins/completion/plugin.py
Labels: type:Bug, component:Code Completion and linting

#21470 PR: Update minimal required version of `pylint` to `>=2.5.0,<3.1`
  .github/scripts/install.sh
  binder/environment.yml
  external-deps/python-lsp-server/.gitrepo
  external-deps/python-lsp-server/CHANGELOG.md
  external-deps/python-lsp-server/CONFIGURATION.md
  external-deps/python-lsp-server/docs/autoimport.md
  external-deps/python-lsp-server/pylsp/_utils.py
  external-deps/python-lsp-server/pylsp/config/config.py
  external-deps/python-lsp-server/pylsp/config/flake8_conf.py
  external-deps/python-lsp-server/pylsp/config/schema.json
  external-deps/python-lsp-server/pylsp/hookspecs.py
  external-deps/python-lsp-server/pylsp/plugins/definition.py
  external-deps/python-lsp-server/pylsp/plugins/flake8_lint.py
  external-deps/python-lsp-server/pylsp/plugins/jedi_rename.py
  external-deps/python-lsp-server/pylsp/plugins/rope_autoimport.py
  external-deps/python-lsp-server/pylsp/plugins/rope_rename.py
  external-deps/python-lsp-server/pylsp/python_lsp.py
  external-deps/python-lsp-server/pylsp/workspace.py
  external-deps/python-lsp-server/pyproject.toml
  external-deps/python-lsp-server/test/fixtures.py
  external-deps/python-lsp-server/test/plugins/test_autoimport.py
  external-deps/python-lsp-server/test/plugins/test_definitions.py
  external-deps/python-lsp-server/test/plugins/test_jedi_rename.py
  external-deps/python-lsp-server/test/plugins/test_rope_rename.py
  external-deps/python-lsp-server/test/test_configuration.py
  external-deps/python-lsp-server/test/test_language_server.py
  external-deps/python-lsp-server/test/test_notebook_document.py
  external-deps/python-lsp-server/test/test_utils.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/plugins/pylint/utils.py
Labels: type:Enhancement, component:Pylint
