Repository spyder-ide/spyder, pull requests merged in 2023-09, with the labels that each got.

#21298 PR: Update core dependencies for 6.0.0.alpha2
  .github/workflows/build-subrepos.yml
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_iofuncs.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#21300 PR: Remove installers workflow step validation for spyder conda package build to be done only on PRs (CI)
  .github/workflows/installers-conda.yml
Labels: type:Task

#21305 PR: Do not sign or notarize macOS installer pkg
  .github/workflows/installers-conda.yml
Labels: OS:MacOS, Installers

#21306 PR: Update `RELEASE.md` instructions and bump `spyder-kernels` version used in the IPython Console validations
  RELEASE.md
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Bug, component:IPython Console, type:Task

#21323 PR: Fix some failing tests
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
  spyder/plugins/editor/widgets/editorstack/editorstack.py
  spyder/plugins/editor/widgets/editorstack/tests/test_editorstack.py
Labels: type:Task

#21249 PR: Remove Kite completion provider code
  .github/scripts/modules_test.sh
  NOTICE.txt
  spyder/app/tests/conftest.py
  spyder/images/dark/kite.svg
  spyder/images/kite/kite_completions.png
  spyder/images/kite/kite_copilot.png
  spyder/images/light/kite.svg
  spyder/plugins/completion/plugin.py
  spyder/plugins/completion/providers/kite/__init__.py
  spyder/plugins/completion/providers/kite/bloomfilter/__init__.py
  spyder/plugins/completion/providers/kite/bloomfilter/kite.bloom
  spyder/plugins/completion/providers/kite/client.py
  spyder/plugins/completion/providers/kite/decorators.py
  spyder/plugins/completion/providers/kite/parsing/__init__.py
  spyder/plugins/completion/providers/kite/parsing/tests/__init__.py
  spyder/plugins/completion/providers/kite/parsing/tests/test_parsing.py
  spyder/plugins/completion/providers/kite/provider.py
  spyder/plugins/completion/providers/kite/providers/__init__.py
  spyder/plugins/completion/providers/kite/providers/document.py
  spyder/plugins/completion/providers/kite/utils/__init__.py
  spyder/plugins/completion/providers/kite/utils/install.py
  spyder/plugins/completion/providers/kite/utils/status.py
  spyder/plugins/completion/providers/kite/utils/tests/__init__.py
  spyder/plugins/completion/providers/kite/utils/tests/test_install.py
  spyder/plugins/completion/providers/kite/widgets/__init__.py
  spyder/plugins/completion/providers/kite/widgets/install.py
  spyder/plugins/completion/providers/kite/widgets/messagebox.py
  spyder/plugins/completion/providers/kite/widgets/status.py
  spyder/plugins/completion/tests/conftest.py
  spyder/plugins/editor/widgets/codeeditor/tests/conftest.py
  spyder/plugins/editor/widgets/codeeditor/tests/test_introspection.py
  spyder/plugins/statusbar/plugin.py
  spyder/utils/external/pybloom_pyqt/__init__.py
  spyder/utils/external/pybloom_pyqt/pybloom.py
  spyder/utils/external/pybloom_pyqt/utils.py
Labels: type:Techdebt, type:Task

#21333 Fix syntax in test_namespacebrowser.py for Python 3.8 and 3.9
  spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
Labels: type:Bug, component:Variable Explorer

#21335 PR: Bump minimal required version of `python-lsp-server` (Dependencies)
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#21334 PR: Fix Codesigning for the Installers and Run Workflow on Schedule
  .github/workflows/build-subrepos.yml
  .github/workflows/installers-conda.yml
  installers-conda/build-environment.yml
  installers-conda/certkeychain.sh
Labels: type:Bug, Installers

#21341 PR: Bump `python-lsp-server` version when using Spyder in dev mode
  setup.py
Labels: type:Task

#21102 PR: Fix error when running main window tests and failing tests
  conftest.py
  spyder/app/tests/conftest.py
  spyder/app/tests/test_mainwindow.py
  spyder/plugins/switcher/tests/test_switcher.py
  spyder/plugins/switcher/widgets/switcher.py
  spyder/tests/test_dependencies_in_sync.py
  spyder/utils/environ.py
Labels: type:Task

#21276 PR: More UI fixes in several places
  spyder/api/widgets/main_widget.py
  spyder/api/widgets/mixins.py
  spyder/plugins/debugger/widgets/framesbrowser.py
  spyder/plugins/editor/plugin.py
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/history/tests/test_plugin.py
  spyder/plugins/history/widgets.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/variableexplorer/widgets/namespacebrowser.py
  spyder/utils/stylesheet.py
  spyder/widgets/comboboxes.py
  spyder/widgets/findreplace.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/tabs.py
  spyder/widgets/tests/test_findreplace.py
Labels: type:Bug, component:Editor, component:IPython Console, component:History Log, User Interface (UI), component:Find in files, component:Find and Replace

#21294 PR: Rename `External Console` plugin to `External Terminal`
  setup.py
  spyder/api/plugins/enum.py
  spyder/app/tests/test_mainwindow.py
  spyder/plugins/externalterminal/__init__.py
  spyder/plugins/externalterminal/api.py
  spyder/plugins/externalterminal/plugin.py
  spyder/plugins/externalterminal/widgets/__init__.py
  spyder/plugins/externalterminal/widgets/run_conf.py
Labels: type:Task

#21368 PR: Add link to Sphinx type of docstrings in Editor's config page
  spyder/plugins/editor/confpage.py
Labels: type:Enhancement, component:Editor, component:Preferences

#21367 PR: Bump Jedi upper bound to `<0.20.0`
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#21372 PR: Ensure no source files have useless shebangs
  spyder/app/restart.py
  spyder/plugins/editor/widgets/tests/assets/ipython_file.ipy
  spyder/utils/external/github.py
  tools/rm_whitespace.py
Labels: type:Task

#21369 PR: Improve syntax highlighting of match/case keywords (Editor)
  spyder/utils/syntaxhighlighters.py
Labels: type:Bug, component:Editor, User Interface (UI)

#21352 Add an empty message to the Debugger pane
  spyder/plugins/debugger/widgets/framesbrowser.py
Labels: type:Enhancement, component:Debugger, User Interface (UI), User Experience (UX)

#21374 PR: Move main and plugin windows to the primary screen if not in a visible location at startup
  spyder/api/widgets/auxiliary_widgets.py
  spyder/api/widgets/main_widget.py
  spyder/api/widgets/mixins.py
  spyder/app/mainwindow.py
Labels: type:Bug, User Experience (UX), component:Main Window
