Repository spyder-ide/spyder, pull requests merged in 2024-06, with the labels that each got.

#22143 PR: Add new icons to be used in the Debugger toolbar
  spyder/images/dark/go_to_editor.svg
  spyder/images/dark/interrupt_and_debug.svg
  spyder/images/dark/list_breakpoints.svg
  spyder/images/light/go_to_editor.svg
  spyder/images/light/interrupt_and_debug.svg
  spyder/images/light/list_breakpoints.svg
Labels: type:Enhancement, component:Debugger, User Interface (UI)

#22156 PR: Fix error when we can't detect Spyder in `conda list` output (Utils)
  spyder/utils/conda.py
Labels: type:Bug, component:Main Window

#22162 PR: Update core dependencies for 5.5.5
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#22163 PR: Improve UI/UX of the Debugger pane
  spyder/app/tests/test_mainwindow.py
  spyder/images/dark/go_to_editor.svg
  spyder/images/dark/interrupt_and_debug.svg
  spyder/images/dark/postmortem_debug.svg
  spyder/images/light/go_to_editor.svg
  spyder/images/light/interrupt_and_debug.svg
  spyder/images/light/postmortem_debug.svg
  spyder/plugins/debugger/widgets/breakpoint_table_view.py
  spyder/plugins/debugger/widgets/framesbrowser.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/utils/icon_manager.py
Labels: type:Enhancement, component:Debugger, User Interface (UI), User Experience (UX)

#22155 PR: Use `jupyter_server` instead of `jupyterhub` for remote client plugin
  spyder/plugins/remoteclient/api/client.py
Labels: type:Enhancement, component:Remote client

#22137 PR: Fix conflict between AsyncDispatcher and `run_sync` function of `jupyter_core`
  spyder/api/asyncdispatcher.py
Labels: type:Bug, component:Remote client

#22141 PR: Improve UI/UX of the Run plugin configuration widgets
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/api/widgets/menus.py
  spyder/app/tests/conftest.py
  spyder/app/tests/test_mainwindow.py
  spyder/app/utils.py
  spyder/config/main.py
  spyder/dependencies.py
  spyder/plugins/debugger/plugin.py
  spyder/plugins/editor/confpage.py
  spyder/plugins/editor/plugin.py
  spyder/plugins/editor/widgets/main_widget.py
  spyder/plugins/externalterminal/plugin.py
  spyder/plugins/externalterminal/widgets/run_conf.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/widgets/run_conf.py
  spyder/plugins/mainmenu/plugin.py
  spyder/plugins/profiler/plugin.py
  spyder/plugins/profiler/widgets/run_conf.py
  spyder/plugins/pylint/plugin.py
  spyder/plugins/run/api.py
  spyder/plugins/run/confpage.py
  spyder/plugins/run/container.py
  spyder/plugins/run/models.py
  spyder/plugins/run/plugin.py
  spyder/plugins/run/tests/test_run.py
  spyder/plugins/run/widgets.py
  spyder/plugins/shortcuts/widgets/table.py
  spyder/utils/icon_manager.py
  spyder/utils/qthelpers.py
  spyder/utils/stylesheet.py
  spyder/widgets/collapsible.py
  spyder/widgets/collectionseditor.py
  spyder/widgets/config.py
  spyder/widgets/elementstable.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/sidebardialog.py
  spyder/widgets/tests/test_collectioneditor.py
Labels: type:Enhancement, User Interface (UI), User Experience (UX), component:Run

#22177 PR: Update core dependencies for 6.0.0 beta2
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Task

#22185 PR: Update translations for 6.0.0
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/te/LC_MESSAGES/spyder.po
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Labels: type:Task

#22197 PR: Address small PySide2 compatibility issues
  spyder/plugins/editor/widgets/editorstack/editorstack.py
  spyder/plugins/editor/widgets/splitter.py
Labels: type:Bug, Package:PySide

#22202 PR: Fix issue where macOS installer update fails to launch Spyder
  installers-conda/build_installers.py
  spyder/plugins/updatemanager/scripts/install.sh
Labels: type:Bug, type:Enhancement, Installers
