Repository spyder-ide/spyder, pull requests merged in 2024-03, with the labels that each got.

#21851 PR: Fix visibility of status bar widget that checks for Spyder updates (Application)
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/workers/updates.py
Labels: type:Bug, User Interface (UI)

#21812 PR: Change default resolution of plots to 144 dpi
  spyder/config/main.py
  spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
Labels: type:Enhancement, component:Plots

#21848 PR: Add icons for the remote connection dialog
  spyder/images/dark/connected.svg
  spyder/images/dark/connecting.svg
  spyder/images/dark/disconnected.svg
  spyder/images/dark/error.svg
  spyder/images/light/connected.svg
  spyder/images/light/connecting.svg
  spyder/images/light/disconnected.svg
  spyder/images/light/error.svg
Labels: type:Enhancement, User Interface (UI)

#21857 PR: UI improvements to configuration pages and other widgets
  spyder/api/preferences.py
  spyder/plugins/appearance/tests/test_confpage.py
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/projects/widgets/main_widget.py
  spyder/plugins/shortcuts/widgets/table.py
  spyder/utils/icon_manager.py
  spyder/utils/palette.py
  spyder/utils/stylesheet.py
  spyder/widgets/arraybuilder.py
  spyder/widgets/config.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/mixins.py
  spyder/widgets/sidebardialog.py
  spyder/widgets/tests/test_array_builder.py
Labels: type:Enhancement, component:IPython Console, component:Preferences, User Interface (UI), User Experience (UX)

#21843 PR: Add `condabin` directory, relative to `sys.executable` and provided `pyexec`, to paths searched for conda executable
  spyder/utils/conda.py
  spyder/utils/programs.py
  spyder/utils/tests/test_conda.py
Labels: type:Bug, component:IPython Console

#21871 PR: Fix issue where Spyder started automatically before conda-based installer exited
  installers-conda/resources/post-install.bat
Labels: type:Bug, OS:Windows, Installers

#21880 PR: Add missing string for translation (Tours)
  spyder/plugins/tours/tours.py
Labels: type:Bug, User Interface (UI)

#21868 PR: Fix showing update status bar widget in our apps at startup and other fixes to the update process (Application)
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/workers/updates.py
Labels: type:Bug, User Interface (UI), User Experience (UX), Installers

#21875 PR: Allow magic to edit locals while debugging
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/customize/code_runner.py
  external-deps/spyder-kernels/spyder_kernels/customize/spyderpdb.py
  external-deps/spyder-kernels/spyder_kernels/customize/utils.py
  spyder/app/tests/test_mainwindow.py
Labels: type:Enhancement, component:IPython Console

#21883 PR: Add icon to represent clearing the console (IPython console)
  spyder/images/dark/clear_console.svg
  spyder/images/light/clear_console.svg
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Enhancement, component:IPython Console, User Interface (UI)

#21911 PR: Update `RELEASE` notes regarding sdist/wheel building and update installers section
  RELEASE.md
Labels: type:Task

#21910 PR: Fix validation to use Spyder 5 installer names when needed
  spyder/workers/updates.py
Labels: type:Bug, Installers

#21353 PR: Initial Editor migration to the new API
  runtests.py
  spyder/api/plugin_registration/registry.py
  spyder/api/plugins/new_api.py
  spyder/api/widgets/menus.py
  spyder/api/widgets/mixins.py
  spyder/api/widgets/toolbars.py
  spyder/app/mainwindow.py
  spyder/app/tests/conftest.py
  spyder/app/tests/test_mainwindow.py
  spyder/config/gui.py
  spyder/config/manager.py
  spyder/plugins/completion/providers/languageserver/provider.py
  spyder/plugins/console/plugin.py
  spyder/plugins/console/widgets/console.py
  spyder/plugins/debugger/plugin.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/plugins/editor/extensions/docstring.py
  spyder/plugins/editor/plugin.py
  spyder/plugins/editor/tests/conftest.py
  spyder/plugins/editor/tests/test_plugin.py
  spyder/plugins/editor/utils/autosave.py
  spyder/plugins/editor/utils/bookmarks.py
  spyder/plugins/editor/utils/switcher_manager.py
  spyder/plugins/editor/widgets/base.py
  spyder/plugins/editor/widgets/codeeditor/codeeditor.py
  spyder/plugins/editor/widgets/editorstack/editorstack.py
  spyder/plugins/editor/widgets/editorstack/tests/conftest.py
  spyder/plugins/editor/widgets/editorstack/tests/test_editorstack.py
  spyder/plugins/editor/widgets/editorstack/tests/test_editorstack_and_outline.py
  spyder/plugins/editor/widgets/editorstack/tests/test_save.py
  spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
  spyder/plugins/editor/widgets/main_widget.py
  spyder/plugins/editor/widgets/splitter.py
  spyder/plugins/editor/widgets/tests/test_editorsplitter.py
  spyder/plugins/editor/widgets/window.py
  spyder/plugins/externalterminal/plugin.py
  spyder/plugins/history/plugin.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/layout/plugin.py
  spyder/plugins/outlineexplorer/plugin.py
  spyder/plugins/profiler/plugin.py
  spyder/plugins/projects/plugin.py
  spyder/plugins/pylint/plugin.py
  spyder/plugins/run/container.py
  spyder/plugins/run/plugin.py
  spyder/plugins/switcher/widgets/proxymodel.py
  spyder/plugins/toolbar/plugin.py
  spyder/plugins/tours/widgets.py
  spyder/plugins/variableexplorer/widgets/main_widget.py
  spyder/utils/qthelpers.py
  spyder/widgets/calltip.py
Labels: component:Editor, type:Techdebt, type:Task

#21918 PR: Add validation for `editor.sideareas_color` over debugger panel
  spyder/plugins/debugger/panels/debuggerpanel.py
Labels: component:Editor, component:Debugger

#21926 PR: Add bening error when `debugpy` is not available (IPython console)
  spyder/api/shellconnect/main_widget.py
  spyder/plugins/ipythonconsole/widgets/client.py
Labels: type:Bug, component:IPython Console

#21844 PR: Make `SpyderPalette` inherit from QDarkStyle palettes and remove `QStylePalette`
  spyder/api/widgets/comboboxes.py
  spyder/api/widgets/menus.py
  spyder/api/widgets/status.py
  spyder/app/mainwindow.py
  spyder/app/utils.py
  spyder/plugins/appearance/confpage.py
  spyder/plugins/completion/providers/languageserver/conftabs/introspection.py
  spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
  spyder/plugins/console/widgets/console.py
  spyder/plugins/debugger/widgets/breakpoint_table_view.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/plugins/editor/panels/codefolding.py
  spyder/plugins/editor/widgets/codeeditor/codeeditor.py
  spyder/plugins/editor/widgets/editorstack/editorstack.py
  spyder/plugins/editor/widgets/splitter.py
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/findinfiles/widgets/results_browser.py
  spyder/plugins/findinfiles/widgets/tests/test_widgets.py
  spyder/plugins/help/widgets.py
  spyder/plugins/ipythonconsole/widgets/client.py
  spyder/plugins/ipythonconsole/widgets/control.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/mainmenu/plugin.py
  spyder/plugins/plots/widgets/figurebrowser.py
  spyder/plugins/plots/widgets/main_widget.py
  spyder/plugins/preferences/widgets/configdialog.py
  spyder/plugins/profiler/widgets/main_widget.py
  spyder/plugins/pylint/main_widget.py
  spyder/plugins/shortcuts/widgets/table.py
  spyder/plugins/tours/widgets.py
  spyder/plugins/variableexplorer/widgets/dataframeeditor.py
  spyder/utils/icon_manager.py
  spyder/utils/palette.py
  spyder/utils/qthelpers.py
  spyder/utils/stylesheet.py
  spyder/widgets/arraybuilder.py
  spyder/widgets/browser.py
  spyder/widgets/calltip.py
  spyder/widgets/dependencies.py
  spyder/widgets/dock.py
  spyder/widgets/elementstable.py
  spyder/widgets/helperwidgets.py
  spyder/widgets/mixins.py
  spyder/widgets/sidebardialog.py
  spyder/widgets/tabs.py
Labels: type:Enhancement, type:Task

#21934 PR: Correct icon colors for remote connection dialog following WCAG 2 guidelines
  spyder/images/dark/connected.svg
  spyder/images/dark/connecting.svg
  spyder/images/dark/disconnected.svg
  spyder/images/dark/error.svg
  spyder/images/light/connected.svg
  spyder/images/light/connecting.svg
  spyder/images/light/disconnected.svg
  spyder/images/light/error.svg
  spyder/utils/palette.py
Labels: type:Bug, User Interface (UI)

#21913 PR: Fix issues with scrolling in dataframe editor
  spyder/plugins/variableexplorer/widgets/dataframeeditor.py
  spyder/plugins/variableexplorer/widgets/tests/test_dataframeeditor.py
Labels: type:Bug, component:Variable Explorer

#21939 PR: Update QtAwesome version constraint to `>=1.3.1,<1.4.0`
  binder/environment.yml
  installers-conda/build-environment.yml
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#21942 PR: Bump pylint to `>=3.1,4` and python-lsp-server to `>=1.11.0,<1.12.0`
  binder/environment.yml
  external-deps/python-lsp-server/.gitrepo
  external-deps/python-lsp-server/CHANGELOG.md
  external-deps/python-lsp-server/CONTRIBUTING.md
  external-deps/python-lsp-server/README.md
  external-deps/python-lsp-server/pylsp/_utils.py
  external-deps/python-lsp-server/pylsp/plugins/flake8_lint.py
  external-deps/python-lsp-server/pylsp/plugins/jedi_rename.py
  external-deps/python-lsp-server/pylsp/plugins/pylint_lint.py
  external-deps/python-lsp-server/pylsp/plugins/rope_autoimport.py
  external-deps/python-lsp-server/pylsp/plugins/rope_rename.py
  external-deps/python-lsp-server/pylsp/python_lsp.py
  external-deps/python-lsp-server/pylsp/uris.py
  external-deps/python-lsp-server/pyproject.toml
  external-deps/python-lsp-server/test/conftest.py
  external-deps/python-lsp-server/test/plugins/test_autoimport.py
  external-deps/python-lsp-server/test/plugins/test_rope_rename.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task
