Repository spyder-ide/spyder, pull requests merged in 2024-09, with the labels that each got.

#22404 PR: Resolve issue where splash screen was incorrectly rendered if conda environment is not activated (Installers)
  binder/environment.yml
  requirements/main.yml
  setup.py
  spyder/app/start.py
  spyder/dependencies.py
Labels: type:Bug, OS:Windows, Installers

#22437 PR: Fix bug when calling `update_edit_menu` at startup (Editor)
  spyder/plugins/editor/widgets/main_widget.py
Labels: type:Bug, component:Editor

#22459 PR: Update workflows to run in the `6.x` branch (CI)
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22460 Backport PR #22459 on branch 6.x (PR: Update workflows to run in the `6.x` branch (CI))
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22438 PR: Enable `autoreload` magic on all operating systems (Config)
  spyder/config/main.py
Labels: type:Bug, component:IPython Console

#22439 Backport PR #22437 on branch 6.x (PR: Fix bug when calling `update_edit_menu` at startup (Editor))
  spyder/plugins/editor/widgets/main_widget.py
Labels: type:Bug, component:Editor

#22462 Backport PR #22438 on branch 6.x (PR: Enable `autoreload` magic on all operating systems (Config))
  spyder/config/main.py
Labels: type:Bug, component:IPython Console

#22465 PR: Update dev version to correctly reflect what `master` is pointing at
  spyder/__init__.py
Labels: type:Task

#22468 PR: Fix development version
  spyder/__init__.py
Labels: type:Task

#22474 PR: Update org.spyder_ide.spyder.appdata.xml
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: OS:Linux, type:Task

#22475 Backport PR #22474 on branch 6.x (PR: Update org.spyder_ide.spyder.appdata.xml)
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: OS:Linux, type:Task

#22476 PR: Fix issues showing the in-app appeal message
  spyder/app/mainwindow.py
  spyder/plugins/application/plugin.py
Labels: type:Bug, component:Main Window

#22477 Backport PR #22476 on branch 6.x (PR: Fix issues showing the in-app appeal message)
  spyder/app/mainwindow.py
  spyder/plugins/application/plugin.py
Labels: type:Bug, component:Main Window

#22488 Backport PR #22484 on branch 6.x (PR: Change default format in array editor to `''`)
  spyder/plugins/variableexplorer/widgets/arrayeditor.py
  spyder/plugins/variableexplorer/widgets/tests/test_arrayeditor.py
Labels: type:Bug, component:Variable Explorer

#22502 PR: Reset `undocked before hiding` state of all plugins before applying layout
  spyder/plugins/layout/api.py
Labels: type:Bug, component:Main Window

#22503 Backport PR #22502 on branch 6.x (PR: Reset `undocked before hiding` state of all plugins before applying layout)
  spyder/plugins/layout/api.py
Labels: type:Bug, component:Main Window

#22504 PR: Don't use script to get env vars if Spyder is launched from a terminal (Utils)
  spyder/utils/environ.py
Labels: type:Bug, component:Pythonpath manager

#22506 Backport PR #22504 on branch 6.x (PR: Don't use script to get env vars if Spyder is launched from a terminal (Utils))
  spyder/utils/environ.py
Labels: type:Bug, component:Pythonpath manager

#22509 PR: Don't kill kernel process tree when running in Binder (IPython console)
  MANIFEST.in
  README.md
  img_src/czi.png
  spyder/config/base.py
  spyder/plugins/ipythonconsole/utils/manager.py
Labels: type:Bug, component:IPython Console

#22510 Backport PR #22509 on branch 6.x (PR: Don't kill kernel process tree when running in Binder (IPython console))
  MANIFEST.in
  README.md
  img_src/czi.png
  spyder/config/base.py
  spyder/plugins/ipythonconsole/utils/manager.py
Labels: type:Bug, component:IPython Console

#22442 PR: Update contributing, release and maintenance instructions for backporting
  Announcements.md
  CONTRIBUTING.md
  MAINTENANCE.md
  RELEASE.md
Labels: type:Task

#22517 Backport PR #22442 on branch 6.x (PR: Update contributing, release and maintenance instructions for backporting)
  Announcements.md
  CONTRIBUTING.md
  MAINTENANCE.md
  RELEASE.md
Labels: type:Task

#22424 PR: Prioritize conda-forge channel so that stable releases are pulled above unstable ones (Installers)
  .github/scripts/installer_test.sh
  .github/workflows/installers-conda.yml
  installers-conda/build_installers.py
Labels: type:Bug, Installers

#22518 Backport PR #22424 on branch 6.x (PR: Prioritize conda-forge channel so that stable releases are pulled above unstable ones (Installers))
  .github/scripts/installer_test.sh
  .github/workflows/installers-conda.yml
  installers-conda/build_installers.py
Labels: type:Bug, Installers

#22490 PR: Prevent error when updating `sys.path` in consoles (IPython console)
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console

#22523 Backport PR #22490 on branch 6.x (PR: Prevent error when updating `sys.path` in consoles (IPython console))
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console

#22530 PR: Update translations for 6.0.1
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/te/LC_MESSAGES/spyder.po
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Labels: type:Task

#22501 PR: Show banner when the kernel is ready (IPython console)
  spyder/config/base.py
  spyder/plugins/ipythonconsole/comms/kernelcomm.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/ipythonconsole/widgets/status.py
Labels: type:Bug, component:IPython Console

#22534 PR: Prevent error when unmaximizing plugins (Main window)
  spyder/app/mainwindow.py
Labels: type:Bug, component:Main Window

#22537 Backport PR #22534 on branch 6.x (PR: Prevent error when unmaximizing plugins (Main window))
  spyder/app/mainwindow.py
Labels: type:Bug, component:Main Window

#22535 Backport PR #22501 on branch 6.x (PR: Show banner when the kernel is ready (IPython console) )
  spyder/config/base.py
  spyder/plugins/ipythonconsole/comms/kernelcomm.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/ipythonconsole/widgets/status.py
Labels: type:Bug, component:IPython Console

#22539 PR: Add step to `RELEASE.md` to update metadata files (`org.spyder_ide.spyder.appdata.xml`)
  RELEASE.md
Labels: type:Task

#22540 Backport PR #22539 on branch 6.x (PR: Add step to `RELEASE.md` to update metadata files (`org.spyder_ide.spyder.appdata.xml`))
  RELEASE.md
Labels: type:Task

#22550 PR: Avoid crashes at startup due to faulty/outdated external plugins
  spyder/app/find_plugins.py
Labels: type:Enhancement, component:Main Window

#22549 PR: Prevent storing a negative position when saving the main window settings (Layout)
  spyder/plugins/layout/plugin.py
Labels: type:Bug, component:Main Window

#22552 Backport PR #22549 on branch 6.x (PR: Prevent storing a negative position when saving the main window settings (Layout))
  spyder/plugins/layout/plugin.py
Labels: type:Bug, component:Main Window

#22553 Backport PR #22550 on branch 6.x (PR: Avoid crashes at startup due to faulty/outdated external plugins)
  spyder/app/find_plugins.py
Labels: type:Enhancement, component:Main Window

#22557 PR: Update `Changelog`, `Announcements` and metadata files for 6.0.1
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#22558 Backport PR #22557 on branch 6.x (PR: Update `Changelog`, `Announcements` and metadata files for 6.0.1)
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#22559 PR: Some improvements to Changelog and Announcements for 6.0.1
  Announcements.md
  changelogs/Spyder-6.md
Labels: type:Task

#22560 Backport PR #22559 on branch 6.x (PR: Some improvements to Changelog and Announcements for 6.0.1)
  Announcements.md
  changelogs/Spyder-6.md
Labels: type:Task

#22577 PR: Pin micromamba to the last version before 2.0 to prevent hangs (CI)
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22582 Backport PR #22577 on branch 6.x (PR: Pin micromamba to the last version before 2.0 to prevent hangs (CI))
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22600 PR: Add `automerge` workflow for automatic merges (CI)
  .github/workflows/automerge.yml
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22594 PR: Set shell banner attribute to be the one computed by us (IPython console)
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console

#22604 PR: Try to fix `automerge` action (CI)
  .github/workflows/automerge.yml
Labels: type:Task

#22605 PR: Remove automerge workflow (CI)
  .github/workflows/automerge.yml
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-win.yml
Labels: type:Task, automerge

#22601 Backport PR #22594 on branch 6.x (PR: Set shell banner attribute to be the one computed by us (IPython console))
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console, automerge

#22595 PR: Dock all undocked plugins before applying a layout
  spyder/plugins/layout/api.py
Labels: type:Bug, component:Main Window

#22610 Backport PR #22595 on branch 6.x (PR: Dock all undocked plugins before applying a layout)
  spyder/plugins/layout/api.py
Labels: type:Bug, component:Main Window, automerge
