Repository spyder-ide/spyder, pull requests merged in 2024-04, with the labels that each got.

#21947 PR: Fix starting kernels in conda envs placed in directories with spaces (IPython console)
  spyder/plugins/ipythonconsole/scripts/conda-activate.bat
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Bug, OS:Windows, component:IPython Console

#21948 PR: Fix getting IPython version for external conda environments (IPython console)
  spyder/plugins/ipythonconsole/widgets/main_widget.py
Labels: type:Bug, component:IPython Console

#21953 PR: Use `notarytool` instead of `altool` (Installers)
  .github/workflows/installer-macos.yml
  installers/macOS/notarize.sh
Labels: OS:MacOS, type:Task, Installers

#21954 PR: Prevent error when we don't get git output to update the `VCSStatus` widget (Editor)
  spyder/plugins/editor/widgets/status.py
Labels: type:Bug, component:IPython Console

#21968 PR: Update `pytest` constraint to `<8.0`
  binder/environment.yml
  requirements/tests.yml
  setup.py
Labels: type:Task, upstream

#21964 PR: Fix micromamba based kernel env activation (IPython console)
  spyder/plugins/ipythonconsole/scripts/conda-activate.bat
Labels: type:Bug, OS:Windows, component:IPython Console

#21945 PR: Remove icons from standard buttons in dialogs (UI/UX)
  spyder/api/widgets/dialogs.py
  spyder/api/widgets/menus.py
  spyder/plugins/appearance/widgets.py
  spyder/plugins/application/widgets/about.py
  spyder/plugins/completion/providers/languageserver/widgets/serversconfig.py
  spyder/plugins/completion/providers/snippets/widgets/snippetsconfig.py
  spyder/plugins/editor/widgets/autosaveerror.py
  spyder/plugins/editor/widgets/gotoline.py
  spyder/plugins/editor/widgets/recover.py
  spyder/plugins/explorer/widgets/explorer.py
  spyder/plugins/explorer/widgets/fileassociations.py
  spyder/plugins/ipythonconsole/widgets/kernelconnect.py
  spyder/plugins/layout/widgets/dialog.py
  spyder/plugins/mainmenu/plugin.py
  spyder/plugins/preferences/widgets/configdialog.py
  spyder/plugins/projects/widgets/projectdialog.py
  spyder/plugins/pythonpath/widgets/pathmanager.py
  spyder/plugins/run/widgets.py
  spyder/utils/stylesheet.py
  spyder/widgets/dependencies.py
  spyder/widgets/sidebardialog.py
Labels: type:Enhancement, User Interface (UI)

#21975 PR: Reapply dock tabbar style if previous session was a Spyder 6 one (Layout)
  spyder/plugins/layout/plugin.py
Labels: type:Bug, User Interface (UI)

#21998 PR: Fix macOS check when defining installer name string for download (Installers)
  spyder/workers/updates.py
Labels: type:Bug, Installers

#21836 PR: Only show UpdateManager statusbar widget while updating and when updates are available
  .github/workflows/installers-conda.yml
  installers-conda/build_installers.py
  pyproject.toml
  spyder/__init__.py
  spyder/plugins/updatemanager/container.py
  spyder/plugins/updatemanager/plugin.py
  spyder/plugins/updatemanager/scripts/install.bat
  spyder/plugins/updatemanager/scripts/install.sh
  spyder/plugins/updatemanager/widgets/status.py
  spyder/plugins/updatemanager/widgets/update.py
  spyder/plugins/updatemanager/workers.py
Labels: type:Enhancement, User Experience (UX)

#22006 PR: Fix adding corner widgets in dockable plugins (API)
  spyder/api/widgets/__init__.py
  spyder/api/widgets/auxiliary_widgets.py
  spyder/api/widgets/main_container.py
  spyder/api/widgets/main_widget.py
  spyder/plugins/ipythonconsole/api.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/variableexplorer/widgets/main_widget.py
  spyder/utils/qthelpers.py
Labels: type:Bug, component:IPython Console, User Interface (UI)

#21997 PR: Avoid iterating over non-dict objects if conda responds with errors
  spyder/utils/conda.py
Labels: type:Bug, component:Main Window

#22017 PR: Update core dependencies for 6.0.0 alpha5
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Task

#22024 PR: Fixes to improve compatibility with PySide2
  spyder/plugins/explorer/widgets/explorer.py
  spyder/widgets/collectionseditor.py
Labels: type:Enhancement, Package:PySide

#22041 PR: Add step to upload Windows installer following new naming format on release (CI)
  .github/workflows/installer-win.yml
Labels: OS:Windows, type:Task, Installers

#22028 PR: Quote kernel connection file in conda activation script (IPython Console)
  spyder/plugins/ipythonconsole/scripts/conda-activate.bat
Labels: type:Bug, component:IPython Console
