Repository spyder-ide/spyder, pull requests merged in 2024-10, with the labels that each got.

#22618 PR: Fix `test_copy_paste_autoindent` forcing text over the clipboard to work (Editor)
  spyder/plugins/editor/widgets/codeeditor/tests/test_autoindent.py
Labels: type:Bug, component:Editor

#22619 Backport PR #22618 on branch 6.x (PR: Fix `test_copy_paste_autoindent` forcing text over the clipboard to work (Editor))
  spyder/plugins/editor/widgets/codeeditor/tests/test_autoindent.py
Labels: type:Bug, component:Editor

#22621 PR: Fix setting of working directory in Profiler plugin
  spyder/plugins/profiler/widgets/main_widget.py
Labels: type:Bug, component:Profiler

#22622 Backport PR #22621 on branch 6.x (PR: Fix setting of working directory in Profiler plugin)
  spyder/plugins/profiler/widgets/main_widget.py
Labels: type:Bug, component:Profiler

#22597 PR: Minor updates to the installer
  .github/workflows/installers-conda.yml
  installers-conda/resources/post-install.sh
Labels: type:Bug, Installers

#22627 Backport PR #22597 on branch 6.x (PR: Minor updates to the installer)
  .github/workflows/installers-conda.yml
  installers-conda/resources/post-install.sh
Labels: type:Bug, Installers

#22636 PR: Simplify min/max required versions of spyder-kernels in the stable branch (IPython console)
  external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml
  external-deps/spyder-kernels/.github/workflows/linux-tests.yml
  external-deps/spyder-kernels/.github/workflows/macos-tests.yml
  external-deps/spyder-kernels/.github/workflows/windows-tests.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/README.md
  external-deps/spyder-kernels/spyder_kernels/_version.py
  external-deps/spyder-kernels/spyder_kernels/utils/iofuncs.py
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_iofuncs.py
  setup.py
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Task

#22642 PR: Simplify min/max required versions of spyder-kernels in the master branch (IPython console)
  binder/environment.yml
  external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml
  external-deps/spyder-kernels/.github/workflows/linux-tests.yml
  external-deps/spyder-kernels/.github/workflows/macos-tests.yml
  external-deps/spyder-kernels/.github/workflows/windows-tests.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/README.md
  external-deps/spyder-kernels/spyder_kernels/_version.py
  external-deps/spyder-kernels/spyder_kernels/utils/iofuncs.py
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_iofuncs.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
  spyder/plugins/ipythonconsole/__init__.py
Labels: type:Task

#22633 PR: Fix debug file and cell buttons in Debugger toolbar
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/customize/code_runner.py
  external-deps/spyder-kernels/spyder_kernels/customize/utils.py
  spyder/plugins/ipythonconsole/tests/conftest.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Labels: type:Bug, component:Debugger

#22644 Backport PR #22633 on branch 6.x (PR: Fix debug file and cell buttons in Debugger toolbar)
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/customize/code_runner.py
  external-deps/spyder-kernels/spyder_kernels/customize/utils.py
  spyder/plugins/ipythonconsole/tests/conftest.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
Labels: type:Task

#22575 PR: Add harmless OpenCL warning to bening errors (IPython console)
  spyder/plugins/ipythonconsole/widgets/client.py
Labels: type:Bug, component:IPython Console

#22645 Backport PR #22575 on branch 6.x (PR: Add harmless OpenCL warning to bening errors (IPython console))
  spyder/plugins/ipythonconsole/widgets/client.py
Labels: type:Bug, component:IPython Console

#22527 PR: Add initial tests for the remote client
  .github/scripts/install.sh
  .github/scripts/run_tests.sh
  .github/workflows/test-remoteclient.yml
  conftest.py
  runtests.py
  spyder/config/base.py
  spyder/plugins/ipythonconsole/__init__.py
  spyder/plugins/remoteclient/tests/Dockerfile
  spyder/plugins/remoteclient/tests/__init__.py
  spyder/plugins/remoteclient/tests/conftest.py
  spyder/plugins/remoteclient/tests/docker-compose.yml
  spyder/plugins/remoteclient/tests/test_ipythonconsole.py
  spyder/plugins/remoteclient/tests/test_plugin.py
Labels: type:Bug, component:Remote client

#22647 Backport PR #22527 on branch 6.x: (PR: Add initial tests for the Remote client plugin)
  .github/scripts/install.sh
  .github/scripts/run_tests.sh
  .github/workflows/test-remoteclient.yml
  conftest.py
  runtests.py
  spyder/config/base.py
  spyder/plugins/ipythonconsole/__init__.py
  spyder/plugins/remoteclient/tests/Dockerfile
  spyder/plugins/remoteclient/tests/__init__.py
  spyder/plugins/remoteclient/tests/conftest.py
  spyder/plugins/remoteclient/tests/docker-compose.yml
  spyder/plugins/remoteclient/tests/test_ipythonconsole.py
  spyder/plugins/remoteclient/tests/test_plugin.py
Labels: type:Task

#22654 PR: Some small fixes to the Maintenance instructions
  MAINTENANCE.md
Labels: type:Task

#22655 Backport PR #22654 on branch 6.x (PR: Some small fixes to the Maintenance instructions)
  MAINTENANCE.md
Labels: type:Task

#22631 PR: Do not check for updates if Spyder is in a system or managed environment
  spyder/plugins/updatemanager/widgets/update.py
Labels: type:Enhancement, component:Update manager

#22657 Backport PR #22631 on branch 6.x (PR: Do not check for updates if Spyder is in a system or managed environment)
  spyder/plugins/updatemanager/widgets/update.py
Labels: type:Enhancement, component:Update manager

#22664 PR: Manually register the Matplotlib inline backend in case it hasn't
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/console/shell.py
Labels: type:Bug, component:IPython Console

#22665 Backport PR #22664 on branch 6.x (PR: Manually register the Matplotlib inline backend in case it hasn't)
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/console/shell.py
Labels: type:Bug, component:IPython Console

#22663 PR: Purge workflow cache weekly
  .github/workflows/purge-cache.yml
  .github/workflows/test-files.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-remoteclient.yml
  .github/workflows/test-win.yml
Labels: type:Task

#22670 PR: Fix issue where cache keys with spaces are not removed (CI)
  .github/workflows/purge-cache.yml
Labels: type:Task

#22662 PR: Replace `is_anaconda` with `is_conda_env`
  spyder/app/tests/test_mainwindow.py
  spyder/config/tests/test_base.py
  spyder/config/utils.py
  spyder/plugins/completion/providers/languageserver/client.py
  spyder/plugins/editor/widgets/codeeditor/tests/test_introspection.py
  spyder/plugins/editor/widgets/editorstack/editorstack.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/plugins/maininterpreter/tests/test_plugin.py
  spyder/plugins/pylint/main_widget.py
  spyder/plugins/pylint/tests/test_pylint.py
  spyder/plugins/updatemanager/widgets/update.py
  spyder/plugins/updatemanager/workers.py
  spyder/utils/tests/test_conda.py
Labels: type:Techdebt

#22668 PR: Don't use hard-coded path to Python in script shebang used to launch Spyder
  scripts/spyder
Labels: type:Enhancement, OS:Linux

#22676 Backport PR #22668 on branch 6.x (PR: Don't use hard-coded path to Python in script shebang used to launch Spyder)
  scripts/spyder
Labels: type:Enhancement, OS:Linux

#22598 PR: Check for asset availability when checking for updates
  spyder/plugins/updatemanager/tests/test_update_manager.py
  spyder/plugins/updatemanager/widgets/update.py
  spyder/plugins/updatemanager/workers.py
Labels: type:Bug, Installers, component:Update manager

#22684 Backport PR #22598 on branch 6.x (PR: Check for asset availability when checking for updates)
  spyder/plugins/updatemanager/tests/test_update_manager.py
  spyder/plugins/updatemanager/widgets/update.py
  spyder/plugins/updatemanager/workers.py
Labels: type:Bug, Installers, component:Update manager

#22628 PR: Handle case when kernel fault file doesn't exist and show error with info explaining that no connection was possible (IPython Console)
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console

#22694 Backport PR #22628 on branch 6.x (PR: Handle case when kernel fault file doesn't exist and show error with info explaining that no connection was possible (IPython Console))
  spyder/plugins/ipythonconsole/widgets/shell.py
Labels: type:Bug, component:IPython Console

#22699 PR: Add `Help Spyder` entry to the Help menu (Application)
  bootstrap.py
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/plugins/application/widgets/status.py
Labels: type:Enhancement, User Experience (UX), component:Main Window

#22700 Backport PR #22699 on branch 6.x (PR: Add `Help Spyder` entry to the Help menu (Application))
  bootstrap.py
  spyder/plugins/application/container.py
  spyder/plugins/application/plugin.py
  spyder/plugins/application/widgets/status.py
Labels: type:Enhancement, User Experience (UX), component:Main Window

#22656 PR: Always use `utf-8` when handling QByteArray data in `ProcessWorker` (Utils)
  spyder/utils/workers.py
Labels: type:Bug, component:Projects, OS:Windows

#22709 PR: Update installing developer repos to accommodate dist-info
  install_dev_repos.py
Labels: type:Bug, type:Task

#22718 PR: Update QtConsole subrepo to take into account changes to support cursor move actions
  external-deps/qtconsole/.gitrepo
  external-deps/qtconsole/qtconsole/ansi_code_processor.py
  external-deps/qtconsole/qtconsole/console_widget.py
  external-deps/qtconsole/qtconsole/tests/test_ansi_code_processor.py
Labels: component:IPython Console, type:Task

#22720 Backport PR #22709 on branch 6.x (PR: Update installing developer repos to accommodate dist-info)
  install_dev_repos.py
Labels: type:Bug, type:Task

#22721 Backport PR #22718 on branch 6.x (PR: Update QtConsole subrepo to take into account changes to support cursor move actions)
  external-deps/qtconsole/.gitrepo
  external-deps/qtconsole/qtconsole/ansi_code_processor.py
  external-deps/qtconsole/qtconsole/console_widget.py
  external-deps/qtconsole/qtconsole/tests/test_ansi_code_processor.py
Labels: component:IPython Console, type:Task

#22702 PR: Restore buttons that control the debugger to the main toolbar
  spyder/api/_version.py
  spyder/api/widgets/toolbars.py
  spyder/config/main.py
  spyder/plugins/debugger/plugin.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/plugins/run/plugin.py
  spyder/plugins/toolbar/container.py
  spyder/plugins/toolbar/plugin.py
  spyder/plugins/toolbar/tests/__init__.py
  spyder/plugins/toolbar/tests/test_toolbar.py
Labels: type:Bug, component:Debugger, User Experience (UX)

#22742 Backport PR #22702 on branch 6.x (PR: Restore buttons that control the debugger to the main toolbar)
  spyder/api/_version.py
  spyder/api/widgets/toolbars.py
  spyder/config/main.py
  spyder/plugins/debugger/plugin.py
  spyder/plugins/debugger/widgets/main_widget.py
  spyder/plugins/run/plugin.py
  spyder/plugins/toolbar/container.py
  spyder/plugins/toolbar/plugin.py
  spyder/plugins/toolbar/tests/__init__.py
  spyder/plugins/toolbar/tests/test_toolbar.py
Labels: type:Bug, component:Debugger, User Experience (UX)

#22745 PR: Remove unnecessary `return` in a `try/finally` statement (Files)
  spyder/plugins/explorer/widgets/explorer.py
Labels: type:Bug, component:File Explorer

#22691 PR: Provide username, host and port from hostname info in ssh tunnels
  spyder/plugins/ipythonconsole/utils/client.py
Labels: type:Bug, component:IPython Console

#22749 Backport PR #22691 on branch 6.x (PR: Provide username, host and port from hostname info in ssh tunnels)
  spyder/plugins/ipythonconsole/utils/client.py
Labels: type:Bug, component:IPython Console

#22752 PR: Update translations for 6.0.2
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/te/LC_MESSAGES/spyder.po
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Labels: type:Task

#22750 Backport PR #22745 on branch 6.x (PR: Remove unnecessary `return` in a `try/finally` statement (Files))
  spyder/plugins/explorer/widgets/explorer.py
Labels: type:Bug, component:File Explorer

#22759 PR: Update `spyder-kernels` to 3.0.1
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  external-deps/spyder-kernels/spyder_kernels/_version.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#22757 PR: Mention that we need to publish release candidates for stable versions in release instructions
  .github/workflows/installers-conda.yml
  RELEASE.md
  installers-conda/build_installers.py
Labels: type:Task

#22760 PR: Update core dependencies for 6.0.2
  binder/environment.yml
  external-deps/qtconsole/.gitrepo
  external-deps/qtconsole/docs/source/changelog.rst
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#22761 Backport PR #22757 on branch 6.x (PR: Mention that we need to publish release candidates for stable versions in release instructions)
  .github/workflows/installers-conda.yml
  RELEASE.md
  installers-conda/build_installers.py
Labels: type:Task

#22762 Backport PR #22760 on branch 6.x (PR: Update core dependencies for 6.0.2)
  binder/environment.yml
  external-deps/qtconsole/.gitrepo
  external-deps/qtconsole/docs/source/changelog.rst
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#22785 PR: Improve version update instructions on `RELEASE.md`
  RELEASE.md
Labels: type:Task

#22786 Backport PR #22785 on branch 6.x (PR: Improve version update instructions on `RELEASE.md`)
  RELEASE.md
Labels: type:Task

#22787 PR: Update Changelog, Announcements and metadata files for 6.0.2
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#22788 Backport PR #22787 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.2)
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task
