Repository spyder-ide/spyder, pull requests merged in 2025-05, with the labels that each got.

#24307 PR: Treat `frozenset` as `set` in Variable Explorer
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py
  spyder/plugins/variableexplorer/widgets/collectionsdelegate.py
  spyder/widgets/collectionseditor.py
  spyder/widgets/tests/test_collectioneditor.py
Labels: type:Enhancement, component:Variable Explorer

#24327 PR: Add ability to filter elements in `ElementsTable`
  spyder/api/plugin_registration/_confpage.py
  spyder/plugins/debugger/widgets/framesbrowser.py
  spyder/plugins/shortcuts/confpage.py
  spyder/plugins/shortcuts/widgets/table.py
  spyder/plugins/variableexplorer/widgets/namespacebrowser.py
  spyder/widgets/elementstable.py
  spyder/widgets/helperwidgets.py
Labels: type:Enhancement, User Interface (UI)

#24329 PR: Use modern and more fine-grained error types in autosave module (Editor)
  spyder/plugins/editor/utils/autosave.py
Labels: type:Bug, component:Editor

#24331 PR: Rename `PaneEmptyWidget` to `EmptyMessageWidget` (Widgets)
  spyder/api/shellconnect/main_widget.py
  spyder/api/widgets/main_widget.py
  spyder/widgets/dependencies.py
  spyder/widgets/emptymessage.py
  spyder/widgets/helperwidgets.py
Labels: type:Task

#24332 Backport PR #24329 on branch 6.x (PR: Use modern and more fine-grained error types in autosave module (Editor))
  spyder/plugins/editor/utils/autosave.py
Labels: type:Bug, component:Editor

#24330 PR: Display `pathlib.Path` variables and `None` in Variable Explorer
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/utils/nsview.py
  external-deps/spyder-kernels/spyder_kernels/utils/tests/test_nsview.py
Labels: type:Enhancement, component:Variable Explorer

#24314 PR: Updater implementation improvements (Installers)
  installers-conda/resources/post-install.bat
  installers-conda/resources/post-install.sh
  spyder/plugins/updatemanager/scripts/install.bat
  spyder/plugins/updatemanager/scripts/install.sh
  spyder/plugins/updatemanager/widgets/status.py
  spyder/plugins/updatemanager/widgets/update.py
Labels: type:Enhancement, Installers

#24239 PR: Fix width of the Find pane when searching for long strings
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/findinfiles/widgets/results_browser.py
  spyder/widgets/comboboxes.py
Labels: type:Bug, User Interface (UI), component:Find in files

#24334 Backport PR #24239 on branch 6.x (PR: Fix width of the Find pane when searching for long strings)
  spyder/plugins/findinfiles/widgets/main_widget.py
  spyder/plugins/findinfiles/widgets/results_browser.py
  spyder/widgets/comboboxes.py
Labels: type:Bug, User Interface (UI), component:Find in files

#24344 PR: Disable magics and commands to call Python package managers in the IPython console
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/console/shell.py
  external-deps/spyder-kernels/spyder_kernels/console/tests/test_console_kernel.py
Labels: type:Bug, component:IPython Console

#24321 PR: Rename resources to Resources in our runtime environment for macOS case-sensitive file systems (Installers)
  installers-conda/build_installers.py
  installers-conda/resources/post-install.sh
Labels: type:Bug, OS:MacOS, Installers

#24299 PR: Fix opening context menu when clicking the blank area of Files pane
  spyder/plugins/explorer/widgets/explorer.py
Labels: type:Bug, User Experience (UX), component:Find in files

#24348 Backport PR #24299 on branch 6.x (PR: Fix opening context menu when clicking the blank area of Files pane)
  spyder/plugins/explorer/widgets/explorer.py
Labels: type:Bug, User Experience (UX), component:Find in files

#24349 PR: Show message when a mismatch of Python versions prevents to deserialize objects (IPython console)
  spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Labels: type:Bug, component:Variable Explorer, User Experience (UX)

#24353 Backport PR #24349 on branch 6.x (PR: Show message when a mismatch of Python versions prevents to deserialize objects (IPython console))
  spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Labels: type:Bug, component:Variable Explorer, User Experience (UX)

#24338 PR: Make Editor annotations work in lower case
  spyder/plugins/editor/utils/findtasks.py
Labels: type:Enhancement, component:Editor

#24360 Backport PR #24338 on branch 6.x (PR: Make Editor annotations work in lower case)
  spyder/plugins/editor/utils/findtasks.py
Labels: type:Enhancement, component:Editor

#24368 PR: Don't display errors when calling `get_value` (IPython console)
  spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Labels: type:Enhancement, component:IPython Console, User Experience (UX)

#24369 Backport PR #24368 on branch 6.x (PR: Don't display errors when calling `get_value` (IPython console))
  spyder/plugins/ipythonconsole/widgets/namespacebrowser.py
Labels: type:Enhancement, component:IPython Console, User Experience (UX)

#24372 PR: Update translations for 6.0.6
  spyder/locale/de/LC_MESSAGES/spyder.po
  spyder/locale/es/LC_MESSAGES/spyder.po
  spyder/locale/fa/LC_MESSAGES/spyder.po
  spyder/locale/fr/LC_MESSAGES/spyder.po
  spyder/locale/hr/LC_MESSAGES/spyder.po
  spyder/locale/hu/LC_MESSAGES/spyder.po
  spyder/locale/ja/LC_MESSAGES/spyder.po
  spyder/locale/pl/LC_MESSAGES/spyder.po
  spyder/locale/pt_BR/LC_MESSAGES/spyder.po
  spyder/locale/ru/LC_MESSAGES/spyder.po
  spyder/locale/spyder.pot
  spyder/locale/te/LC_MESSAGES/spyder.po
  spyder/locale/uk/LC_MESSAGES/spyder.po
  spyder/locale/zh_CN/LC_MESSAGES/spyder.po
Labels: type:Task

#24389 PR: Don't use cached kernels on Windows with Conda 25.3.0+ (IPython console)
  spyder/plugins/ipythonconsole/utils/kernelspec.py
  spyder/plugins/ipythonconsole/widgets/mixins.py
Labels: type:Task

#24391 Backport PR #24389 on branch 6.x (PR: Don't use cached kernels on Windows with Conda 25.3.0+ (IPython console))
  spyder/plugins/ipythonconsole/utils/kernelspec.py
  spyder/plugins/ipythonconsole/widgets/mixins.py
Labels: type:Task

#24397 PR: Sanity check in `setup.py` will mistakenly let Python 2 pass
  setup.py
Labels: type:Task

#24398 Backport PR #24397 on branch 6.x (PR: Sanity check in `setup.py` will mistakenly let Python 2 pass)
  setup.py
Labels: type:Task

#24315 PR: Improve UI for long file names (Editor)
  spyder/plugins/editor/widgets/editorstack/editorstack.py
Labels: type:Enhancement, component:Editor, User Interface (UI)

#24406 Backport PR #24315 on branch 6.x (PR: Improve UI for long file names (Editor))
  spyder/plugins/editor/widgets/editorstack/editorstack.py
Labels: type:Enhancement, component:Editor, User Interface (UI)

#24407 PR: Update `spyder-kernels` to 3.0.4 (for Spyder 6.0.6)
  binder/environment.yml
  external-deps/spyder-kernels/.github/workflows/linux-pip-tests.yml
  external-deps/spyder-kernels/.github/workflows/linux-tests.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  external-deps/spyder-kernels/spyder_kernels/_version.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#24411 PR: Update Changelog, Announcements and metadata files for 6.0.6
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#24413 Backport PR #24411 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.6)
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#24381 PR : Change shortcut to transform text to uppercase (Editor)
  spyder/config/main.py
  spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
Labels: type:Bug, component:Editor, User Experience (UX)

#24425 PR: Fix cached kernels on Windows for CIs
  .github/scripts/install.sh
  .github/workflows/test-win.yml
Labels: type:Task

#24426 Backport PR #24425 on branch 6.x (PR: Fix cached kernels on Windows for CIs)
  .github/scripts/install.sh
  .github/workflows/test-win.yml
Labels: type:Task

#23986 PR: Add support for displaying remote files (File Explorer, Working Directory)
  changelogs/Spyder-6.md
  spyder/config/main.py
  spyder/plugins/explorer/api.py
  spyder/plugins/explorer/plugin.py
  spyder/plugins/explorer/widgets/explorer.py
  spyder/plugins/explorer/widgets/main_widget.py
  spyder/plugins/explorer/widgets/remote_explorer.py
  spyder/plugins/explorer/widgets/tests/test_explorer.py
  spyder/plugins/ipythonconsole/plugin.py
  spyder/plugins/ipythonconsole/widgets/client.py
  spyder/plugins/ipythonconsole/widgets/main_widget.py
  spyder/plugins/ipythonconsole/widgets/shell.py
  spyder/plugins/workingdirectory/container.py
  spyder/plugins/workingdirectory/plugin.py
Labels: component:File Explorer, type:Feature, component:Working directory, component:Remote client

#24428 Backport PR #24399 on branch 6.x (PR: Try to decrease `test_dedicated_consoles` flakyness (CI/Tests))
  spyder/app/tests/test_mainwindow.py
Labels: type:Task

#24427 PR: Fix executable used for restarts on macOS
  spyder/app/__init__.py
  spyder/app/restart.py
  spyder/app/start.py
  spyder/plugins/application/plugin.py
Labels: type:Bug, OS:MacOS, component:Main Window

#24444 PR: Add shortcut to find/replace widget to replace all found instances
  spyder/config/main.py
  spyder/widgets/findreplace.py
Labels: type:Enhancement, component:Find and Replace

#24448 PR: Fix hard crash when checking conda for cached kernels (IPython console)
  spyder/plugins/ipythonconsole/widgets/mixins.py
Labels: type:Bug, component:IPython Console

#23919 PR: Support activation of Pixi environments
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/spyder_kernels/console/kernel.py
  external-deps/spyder-kernels/spyder_kernels/utils/pythonenv.py
  spyder/plugins/ipythonconsole/utils/kernelspec.py
  spyder/plugins/ipythonconsole/widgets/status.py
  spyder/utils/conda.py
  spyder/utils/programs.py
Labels: type:Enhancement, component:IPython Console

#24449 Backport PR #24448 on branch 6.x (PR: Fix hard crash when checking conda for cached kernels (IPython console))
  spyder/plugins/ipythonconsole/widgets/mixins.py
Labels: type:Bug, component:IPython Console

#24450 PR: Require a minimal version of the `traitlets` package (IPython console)
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/requirements/posix.txt
  external-deps/spyder-kernels/requirements/windows.txt
  external-deps/spyder-kernels/setup.py
Labels: type:Bug, component:IPython Console

#24416 PR: Fix UnboundLocalError when cancelling the open file dialog
  spyder/plugins/application/container.py
Labels: type:Bug, OS:MacOS, component:Main Window

#24455 Backport PR #24450 on branch 6.x (PR: Require a minimal version of the `traitlets` package (IPython console))
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/requirements/posix.txt
  external-deps/spyder-kernels/requirements/windows.txt
  external-deps/spyder-kernels/setup.py
Labels: type:Bug, component:IPython Console

#24458 PR: Update `spyder-kernels` to 3.0.5 (for Spyder 6.0.7)
  binder/environment.yml
  external-deps/spyder-kernels/.gitrepo
  external-deps/spyder-kernels/CHANGELOG.md
  external-deps/spyder-kernels/RELEASE.md
  external-deps/spyder-kernels/spyder_kernels/_version.py
  requirements/main.yml
  setup.py
  spyder/dependencies.py
Labels: type:Task

#24445 PR: Change shortcut to transform text to lowercase (Editor)
  spyder/config/main.py
  spyder/plugins/editor/widgets/editorstack/tests/test_shortcuts.py
Labels: type:Enhancement, component:Editor, User Experience (UX)

#24464 PR: Update Changelog, Announcements and metadata files for 6.0.7
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#24467 Backport PR #24464 on branch 6.x (PR: Update Changelog, Announcements and metadata files for 6.0.7)
  Announcements.md
  changelogs/Spyder-6.md
  scripts/org.spyder_ide.spyder.appdata.xml
Labels: type:Task

#24480 PR: Remove unnecessary margins around `RemoteExplorer` widget (Files)
  spyder/plugins/explorer/widgets/remote_explorer.py
Labels: type:Bug, User Interface (UI), component:File Explorer

#24482 PR: Move filter and refresh actions to be part of the corner widgets (Files)
  spyder/plugins/explorer/widgets/main_widget.py
Labels: component:File Explorer

#24493 PR: Increase minimal supported Python version to 3.9
  .github/scripts/install.sh
  .github/workflows/test-linux.yml
  .github/workflows/test-remoteclient.yml
  README.md
  setup.py
  spyder/app/tests/spyder-boilerplate/setup.py
  spyder/dependencies.py
  spyder/plugins/editor/panels/scrollflag.py
  spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py
  spyder/tests/test_dependencies_in_sync.py
  spyder/utils/tests/test_pyenv.py
Labels: type:Task

#24507 PR: Fix Remote client tests by passing `ClientSession` loop when closing APIs (Jupyter and Files APIs)
  spyder/plugins/explorer/plugin.py
  spyder/plugins/ipythonconsole/widgets/client.py
Labels: component:IPython Console, component:File Explorer, type:Task, component:Remote client

#24491 PR: Make editor annotations be limited to comments
  spyder/plugins/editor/utils/findtasks.py
Labels: type:Bug, component:Editor, User Interface (UI)
